/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Shield, Activity, AlertTriangle, CheckCircle } from "lucide-react";

export default function App() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans">
      {/* Top Navigation */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-indigo-600 p-1.5 rounded-lg">
              <Shield className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-xl font-bold tracking-tight text-slate-900">
              SecurePulse
            </h1>
          </div>
          <nav className="flex items-center gap-4 text-sm font-medium text-slate-600">
            <a href="#" className="text-indigo-600">Daily Brief</a>
            <a href="#" className="hover:text-slate-900 transition-colors">Sources</a>
            <a href="#" className="hover:text-slate-900 transition-colors">Settings</a>
          </nav>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-5xl mx-auto px-4 py-8">
        <div className="mb-8">
          <h2 className="text-2xl font-bold tracking-tight mb-1">Today's Intelligence Brief</h2>
          <p className="text-slate-500">Generated by Gemini 2.0 Flash • {new Date().toLocaleDateString()}</p>
        </div>

        {/* Placeholder for Brief Cards */}
        <div className="space-y-6">
          
          {/* Example Card 1 */}
          <article className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="h-1.5 w-full bg-red-500"></div>
            <div className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-2">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold bg-red-50 text-red-700 border border-red-100">
                    <AlertTriangle className="w-3.5 h-3.5" />
                    CRITICAL
                  </span>
                  <span className="text-sm text-slate-500 font-medium">CISA KEV Addition</span>
                </div>
                <span className="text-xs font-mono text-slate-400">HIGH CONFIDENCE</span>
              </div>
              
              <h3 className="text-xl font-bold mb-3">Active Exploitation of Ivanti Connect Secure (CVE-2024-21893)</h3>
              
              <ul className="space-y-2 mb-6">
                <li className="flex items-start gap-2 text-slate-700">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-slate-400 shrink-0"></div>
                  <p>A server-side request forgery (SSRF) vulnerability in the SAML component allows attackers to bypass authentication.</p>
                </li>
                <li className="flex items-start gap-2 text-slate-700">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-slate-400 shrink-0"></div>
                  <p>Observed in targeted campaigns against aerospace and defense sectors.</p>
                </li>
              </ul>

              <div className="bg-slate-50 rounded-xl p-4 mb-4 border border-slate-100">
                <h4 className="text-sm font-bold text-slate-900 mb-1">Why it matters to you</h4>
                <p className="text-sm text-slate-600">You are subscribed to alerts for "Ivanti". This flaw allows unauthenticated access to internal resources and is currently being exploited in the wild.</p>
              </div>

              <div className="flex items-center justify-between pt-4 border-t border-slate-100">
                <div className="flex items-center gap-2 text-sm font-medium text-emerald-700">
                  <CheckCircle className="w-4 h-4" />
                  Suggested Action: Apply patch version 22.4R2.2 immediately.
                </div>
              </div>
            </div>
          </article>

          {/* Example Card 2 */}
          <article className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="h-1.5 w-full bg-amber-500"></div>
            <div className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-2">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold bg-amber-50 text-amber-700 border border-amber-100">
                    <Activity className="w-3.5 h-3.5" />
                    HIGH
                  </span>
                  <span className="text-sm text-slate-500 font-medium">Threat Campaign</span>
                </div>
                <span className="text-xs font-mono text-slate-400">MEDIUM CONFIDENCE</span>
              </div>
              
              <h3 className="text-xl font-bold mb-3">Scattered Spider Shifts Tactics to Cloud Identity Providers</h3>
              
              <ul className="space-y-2 mb-6">
                <li className="flex items-start gap-2 text-slate-700">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-slate-400 shrink-0"></div>
                  <p>The threat group is increasingly targeting Okta and Entra ID administrators via sophisticated social engineering.</p>
                </li>
                <li className="flex items-start gap-2 text-slate-700">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-slate-400 shrink-0"></div>
                  <p>Bypassing MFA using prompt bombing and SIM swapping techniques.</p>
                </li>
              </ul>

              <div className="bg-slate-50 rounded-xl p-4 mb-4 border border-slate-100">
                <h4 className="text-sm font-bold text-slate-900 mb-1">Why it matters to you</h4>
                <p className="text-sm text-slate-600">Your organization uses Okta (detected via subscriptions). This represents a direct threat to your identity perimeter.</p>
              </div>

              <div className="flex items-center justify-between pt-4 border-t border-slate-100">
                <div className="flex items-center gap-2 text-sm font-medium text-indigo-700">
                  <Shield className="w-4 h-4" />
                  Suggested Action: Enforce FIDO2/WebAuthn hardware keys for all admin accounts.
                </div>
              </div>
            </div>
          </article>

        </div>
      </main>
    </div>
  );
}
