/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useEffect } from "react";
import { Shield, Activity, AlertTriangle, CheckCircle, Sun, Moon } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

function useDarkMode(): [boolean, (v: boolean) => void] {
  const [dark, setDark] = useState(() => {
    try {
      const saved = localStorage.getItem("securepulse-dark");
      if (saved !== null) return saved === "true";
    } catch {}
    return window.matchMedia?.("(prefers-color-scheme: dark)").matches ?? false;
  });

  useEffect(() => {
    document.documentElement.classList.toggle("dark", dark);
    try {
      localStorage.setItem("securepulse-dark", String(dark));
    } catch {}
  }, [dark]);

  return [dark, setDark];
}

export default function App() {
  const [dark, setDark] = useDarkMode();

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#080d17] text-slate-900 dark:text-gray-100 font-sans transition-colors duration-300">

      {/* Top Navigation */}
      <header className="bg-white/80 dark:bg-[#0c1220]/90 border-b border-slate-200 dark:border-indigo-950/60 sticky top-0 z-10 backdrop-blur-md transition-colors duration-300">
        <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="bg-indigo-600 dark:bg-indigo-500 p-1.5 rounded-lg transition-all duration-300 dark:shadow-[0_0_14px_rgba(99,102,241,0.55)]">
              <Shield className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-xl font-bold tracking-tight text-slate-900 dark:text-white">
              SecurePulse
            </h1>
          </div>

          <div className="flex items-center gap-5">
            <nav className="flex items-center gap-4 text-sm font-medium text-slate-600 dark:text-gray-400">
              <a href="#" className="text-indigo-600 dark:text-indigo-400">Daily Brief</a>
              <a href="#" className="hover:text-slate-900 dark:hover:text-white transition-colors">Sources</a>
              <a href="#" className="hover:text-slate-900 dark:hover:text-white transition-colors">Settings</a>
            </nav>

            {/* Dark mode toggle */}
            <button
              onClick={() => setDark(!dark)}
              aria-label={dark ? "Switch to light mode" : "Switch to dark mode"}
              className="relative w-9 h-9 flex items-center justify-center rounded-full bg-slate-100 dark:bg-gray-800/80 hover:bg-slate-200 dark:hover:bg-gray-700 border border-slate-200 dark:border-gray-700/60 transition-all duration-300 cursor-pointer shrink-0"
            >
              <AnimatePresence mode="wait" initial={false}>
                {dark ? (
                  <motion.span
                    key="sun"
                    initial={{ rotate: -90, opacity: 0, scale: 0.4 }}
                    animate={{ rotate: 0, opacity: 1, scale: 1 }}
                    exit={{ rotate: 90, opacity: 0, scale: 0.4 }}
                    transition={{ duration: 0.18, ease: "easeOut" }}
                    className="absolute flex items-center justify-center"
                  >
                    <Sun className="w-4 h-4 text-amber-400" />
                  </motion.span>
                ) : (
                  <motion.span
                    key="moon"
                    initial={{ rotate: 90, opacity: 0, scale: 0.4 }}
                    animate={{ rotate: 0, opacity: 1, scale: 1 }}
                    exit={{ rotate: -90, opacity: 0, scale: 0.4 }}
                    transition={{ duration: 0.18, ease: "easeOut" }}
                    className="absolute flex items-center justify-center"
                  >
                    <Moon className="w-4 h-4 text-slate-500" />
                  </motion.span>
                )}
              </AnimatePresence>
            </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-5xl mx-auto px-4 py-8">
        <div className="mb-8">
          <h2 className="text-2xl font-bold tracking-tight mb-1 dark:text-white">Today's Intelligence Brief</h2>
          <p className="text-slate-500 dark:text-gray-500 text-sm">
            Generated by Gemini Flash &bull; {new Date().toLocaleDateString()}
          </p>
        </div>

        <div className="space-y-6">

          {/* CRITICAL card */}
          <article className="bg-white dark:bg-[#0e1829] rounded-2xl border border-slate-200 dark:border-gray-800/80 shadow-sm dark:shadow-[0_4px_32px_rgba(0,0,0,0.5)] overflow-hidden transition-all duration-300 hover:shadow-md dark:hover:border-red-900/40">
            <div className="h-1.5 w-full bg-red-500 dark:bg-red-600"></div>
            <div className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-2">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold bg-red-50 dark:bg-red-950/50 text-red-700 dark:text-red-400 border border-red-100 dark:border-red-900/40">
                    <AlertTriangle className="w-3.5 h-3.5" />
                    CRITICAL
                  </span>
                  <span className="text-sm text-slate-500 dark:text-gray-500 font-medium">CISA KEV Addition</span>
                </div>
                <span className="text-xs font-mono text-slate-400 dark:text-gray-600">HIGH CONFIDENCE</span>
              </div>

              <h3 className="text-xl font-bold mb-3 dark:text-white">
                Active Exploitation of Ivanti Connect Secure (CVE-2024-21893)
              </h3>

              <ul className="space-y-2 mb-6">
                <li className="flex items-start gap-2 text-slate-700 dark:text-gray-300">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-slate-400 dark:bg-gray-600 shrink-0"></div>
                  <p>A server-side request forgery (SSRF) vulnerability in the SAML component allows attackers to bypass authentication.</p>
                </li>
                <li className="flex items-start gap-2 text-slate-700 dark:text-gray-300">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-slate-400 dark:bg-gray-600 shrink-0"></div>
                  <p>Observed in targeted campaigns against aerospace and defense sectors.</p>
                </li>
              </ul>

              <div className="bg-slate-50 dark:bg-gray-800/50 rounded-xl p-4 mb-4 border border-slate-100 dark:border-gray-700/40">
                <h4 className="text-sm font-bold text-slate-900 dark:text-gray-200 mb-1">Why it matters to you</h4>
                <p className="text-sm text-slate-600 dark:text-gray-400">
                  You are subscribed to alerts for "Ivanti". This flaw allows unauthenticated access to internal resources and is currently being exploited in the wild.
                </p>
              </div>

              <div className="flex items-center justify-between pt-4 border-t border-slate-100 dark:border-gray-800/80">
                <div className="flex items-center gap-2 text-sm font-medium text-emerald-700 dark:text-emerald-400">
                  <CheckCircle className="w-4 h-4" />
                  Suggested Action: Apply patch version 22.4R2.2 immediately.
                </div>
              </div>
            </div>
          </article>

          {/* HIGH card */}
          <article className="bg-white dark:bg-[#0e1829] rounded-2xl border border-slate-200 dark:border-gray-800/80 shadow-sm dark:shadow-[0_4px_32px_rgba(0,0,0,0.5)] overflow-hidden transition-all duration-300 hover:shadow-md dark:hover:border-amber-900/40">
            <div className="h-1.5 w-full bg-amber-500 dark:bg-amber-500"></div>
            <div className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-2">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold bg-amber-50 dark:bg-amber-950/50 text-amber-700 dark:text-amber-400 border border-amber-100 dark:border-amber-900/40">
                    <Activity className="w-3.5 h-3.5" />
                    HIGH
                  </span>
                  <span className="text-sm text-slate-500 dark:text-gray-500 font-medium">Threat Campaign</span>
                </div>
                <span className="text-xs font-mono text-slate-400 dark:text-gray-600">MEDIUM CONFIDENCE</span>
              </div>

              <h3 className="text-xl font-bold mb-3 dark:text-white">
                Scattered Spider Shifts Tactics to Cloud Identity Providers
              </h3>

              <ul className="space-y-2 mb-6">
                <li className="flex items-start gap-2 text-slate-700 dark:text-gray-300">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-slate-400 dark:bg-gray-600 shrink-0"></div>
                  <p>The threat group is increasingly targeting Okta and Entra ID administrators via sophisticated social engineering.</p>
                </li>
                <li className="flex items-start gap-2 text-slate-700 dark:text-gray-300">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-slate-400 dark:bg-gray-600 shrink-0"></div>
                  <p>Bypassing MFA using prompt bombing and SIM swapping techniques.</p>
                </li>
              </ul>

              <div className="bg-slate-50 dark:bg-gray-800/50 rounded-xl p-4 mb-4 border border-slate-100 dark:border-gray-700/40">
                <h4 className="text-sm font-bold text-slate-900 dark:text-gray-200 mb-1">Why it matters to you</h4>
                <p className="text-sm text-slate-600 dark:text-gray-400">
                  Your organization uses Okta (detected via subscriptions). This represents a direct threat to your identity perimeter.
                </p>
              </div>

              <div className="flex items-center justify-between pt-4 border-t border-slate-100 dark:border-gray-800/80">
                <div className="flex items-center gap-2 text-sm font-medium text-indigo-700 dark:text-indigo-400">
                  <Shield className="w-4 h-4" />
                  Suggested Action: Enforce FIDO2/WebAuthn hardware keys for all admin accounts.
                </div>
              </div>
            </div>
          </article>

        </div>
      </main>
    </div>
  );
}
