/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useEffect, useMemo, useState } from "react";
import { Shield, Activity, AlertTriangle, CheckCircle } from "lucide-react";
import type { BriefCard } from "./lib/intel.ts";

type BriefResponse = {
  generatedAt: string;
  tldr: string;
  cards: BriefCard[];
};

const severityStyles = {
  critical: {
    line: "bg-red-500",
    badge: "bg-red-50 text-red-700 border-red-100",
    icon: AlertTriangle,
  },
  high: {
    line: "bg-amber-500",
    badge: "bg-amber-50 text-amber-700 border-amber-100",
    icon: Activity,
  },
  medium: {
    line: "bg-blue-500",
    badge: "bg-blue-50 text-blue-700 border-blue-100",
    icon: Activity,
  },
  low: {
    line: "bg-slate-400",
    badge: "bg-slate-100 text-slate-700 border-slate-200",
    icon: Activity,
  },
} as const;

export default function App() {
  const [brief, setBrief] = useState<BriefResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadBrief() {
      try {
        const response = await fetch("/api/daily-briefs/latest");
        if (!response.ok) {
          throw new Error("Failed to fetch daily brief");
        }

        const data = (await response.json()) as BriefResponse;
        setBrief(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unknown error");
      }
    }

    void loadBrief();
  }, []);

  const dateLabel = useMemo(() => new Date().toLocaleDateString(), []);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans">
      <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-indigo-600 p-1.5 rounded-lg">
              <Shield className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-xl font-bold tracking-tight text-slate-900">SecurePulse</h1>
          </div>
          <nav className="flex items-center gap-4 text-sm font-medium text-slate-600">
            <a href="#" className="text-indigo-600">
              Daily Brief
            </a>
            <a href="#" className="hover:text-slate-900 transition-colors">
              Sources
            </a>
            <a href="#" className="hover:text-slate-900 transition-colors">
              Settings
            </a>
          </nav>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-8">
        <div className="mb-6">
          <h2 className="text-2xl font-bold tracking-tight mb-1">Today's Intelligence Brief</h2>
          <p className="text-slate-500">Generated by Gemini 3 Flash style workflow • {dateLabel}</p>
        </div>

        {brief ? (
          <section className="bg-indigo-50 border border-indigo-100 rounded-2xl p-4 mb-6">
            <p className="text-xs uppercase tracking-wide text-indigo-700 font-semibold mb-1">TL;DR in 30 seconds</p>
            <p className="text-sm text-indigo-900">{brief.tldr}</p>
          </section>
        ) : null}

        {error ? <p className="text-red-700 bg-red-50 border border-red-100 p-3 rounded-xl">{error}</p> : null}

        <div className="space-y-6">
          {brief?.cards.map((card) => {
            const style = severityStyles[card.severity];
            const Icon = style.icon;

            return (
              <article key={card.id} className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
                <div className={`h-1.5 w-full ${style.line}`} />
                <div className="p-6">
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex items-center gap-2">
                      <span
                        className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold border ${style.badge}`}
                      >
                        <Icon className="w-3.5 h-3.5" />
                        {card.severity.toUpperCase()}
                      </span>
                      <span className="text-sm text-slate-500 font-medium">{card.cardType}</span>
                    </div>
                    <span className="text-xs font-mono text-slate-400">{card.confidenceLabel} CONFIDENCE</span>
                  </div>

                  <h3 className="text-xl font-bold mb-3">{card.title}</h3>

                  <ul className="space-y-2 mb-6">
                    {card.bullets.map((bullet) => (
                      <li key={bullet} className="flex items-start gap-2 text-slate-700">
                        <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-slate-400 shrink-0" />
                        <p>{bullet}</p>
                      </li>
                    ))}
                  </ul>

                  <div className="bg-slate-50 rounded-xl p-4 mb-4 border border-slate-100">
                    <h4 className="text-sm font-bold text-slate-900 mb-1">Why it matters to you</h4>
                    <p className="text-sm text-slate-600">{card.whyItMatters}</p>
                  </div>

                  <div className="flex items-center justify-between pt-4 border-t border-slate-100 flex-wrap gap-3">
                    <div className="flex items-center gap-2 text-sm font-medium text-emerald-700">
                      <CheckCircle className="w-4 h-4" />
                      Suggested Action: {card.suggestedAction}
                    </div>
                    <a
                      href={card.sources[0]?.url}
                      target="_blank"
                      rel="noreferrer"
                      className="text-sm text-indigo-700 font-medium hover:underline"
                    >
                      Source: {card.sources[0]?.title}
                    </a>
                  </div>
                </div>
              </article>
            );
          })}
        </div>
      </main>
    </div>
  );
}
